"""fix column email name

Revision ID: f7c628dc9838
Revises: 3525301c63ce
Create Date: 2026-09-12 09:04:23.637499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7c628dc9838'
down_revision: Union[str, Sequence[str], None] = '3525301c63ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('user_emial_key'), 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'emial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emial', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint(op.f('user_emial_key'), 'user', ['emial'], postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
