"""Add email to users

Revision ID: f7fb87eeefd5
Revises: 4c3bf80d6c5d
Create Date: 2026-09-12 08:45:45.685504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7fb87eeefd5'
down_revision: Union[str, Sequence[str], None] = '4c3bf80d6c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('emial', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'emial')
    # ### end Alembic commands ###
