events {}

http {
    server {
        listen 80;
        server_name api.devlop.online;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            # proxy_pass http://backend:8000;
            #Redirect everything else to HTTPS
            return 301 https://api.devlop.online$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name api.devlop.online;

        ssl_certificate /etc/letsencrypt/live/api.devlop.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.devlop.online/privkey.pem;

        location / {
            proxy_pass http://backend:8000;
        }
    }
}
